db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/cart_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
db.username=root
db.password=
db.pool.size=10
